// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DarthPestilane/easytcp (interfaces: Packer)

// Package easytcp is a generated GoMock package.
package easytcp

import (
	io "io"

	gomock "github.com/golang/mock/gomock"
)

// MockPacker is a mock of Packer interface.
type MockPacker struct {
	ctrl     *gomock.Controller
	recorder *MockPackerMockRecorder
}

// MockPackerMockRecorder is the mock recorder for MockPacker.
type MockPackerMockRecorder struct {
	mock *MockPacker
}

// NewMockPacker creates a new mock instance.
func NewMockPacker(ctrl *gomock.Controller) *MockPacker { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacker) EXPECT() *MockPackerMockRecorder {
	_ = "STUB: not implemented"

	// Pack mocks base method.
	return nil
}

func (m *MockPacker) Pack(arg0 *Message) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Pack indicates an expected call of Pack.
func (mr *MockPackerMockRecorder) Pack(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unpack mocks base method.
func (m *MockPacker) Unpack(arg0 io.Reader) (*Message, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Unpack indicates an expected call of Unpack.
func (mr *MockPackerMockRecorder) Unpack(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
