// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DarthPestilane/easytcp (interfaces: Codec)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// MockCodec is a mock of Codec interface.
type MockCodec struct {
	ctrl     *gomock.Controller
	recorder *MockCodecMockRecorder
}

// MockCodecMockRecorder is the mock recorder for MockCodec.
type MockCodecMockRecorder struct {
	mock *MockCodec
}

// NewMockCodec creates a new mock instance.
func NewMockCodec(ctrl *gomock.Controller) *MockCodec { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodec) EXPECT() *MockCodecMockRecorder {
	_ = "STUB: not implemented"

	// Decode mocks base method.
	return nil
}

func (m *MockCodec) Decode(arg0 []byte, arg1 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Decode indicates an expected call of Decode.
func (mr *MockCodecMockRecorder) Decode(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Encode mocks base method.
func (m *MockCodec) Encode(arg0 interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Encode indicates an expected call of Encode.
func (mr *MockCodecMockRecorder) Encode(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
