// Code generated by MockGen. DO NOT EDIT.
// Source: net (interfaces: Listener,Error,Conn)

// Package mock is a generated GoMock package.
package mock

import (
	net "net"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockListener is a mock of Listener interface.
type MockListener struct {
	ctrl     *gomock.Controller
	recorder *MockListenerMockRecorder
}

// MockListenerMockRecorder is the mock recorder for MockListener.
type MockListenerMockRecorder struct {
	mock *MockListener
}

// NewMockListener creates a new mock instance.
func NewMockListener(ctrl *gomock.Controller) *MockListener { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListener) EXPECT() *MockListenerMockRecorder {
	_ = "STUB: not implemented"

	// Accept mocks base method.
	return nil
}

func (m *MockListener) Accept() (net.Conn, error) {
	_ = "STUB: not implemented"
	return *new(net.Conn), nil
}

// Accept indicates an expected call of Accept.
func (mr *MockListenerMockRecorder) Accept() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Addr mocks base method.
func (m *MockListener) Addr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// Addr indicates an expected call of Addr.
func (mr *MockListenerMockRecorder) Addr() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Close mocks base method.
func (m *MockListener) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockListenerMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockError is a mock of Error interface.
type MockError struct {
	ctrl     *gomock.Controller
	recorder *MockErrorMockRecorder
}

// MockErrorMockRecorder is the mock recorder for MockError.
type MockErrorMockRecorder struct {
	mock *MockError
}

// NewMockError creates a new mock instance.
func NewMockError(ctrl *gomock.Controller) *MockError { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockError) EXPECT() *MockErrorMockRecorder {
	_ = "STUB: not implemented"

	// Error mocks base method.
	return nil
}

func (m *MockError) Error() string { _ = "STUB: not implemented"; return "" }

// Error indicates an expected call of Error.
func (mr *MockErrorMockRecorder) Error() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Temporary mocks base method.
func (m *MockError) Temporary() bool { _ = "STUB: not implemented"; return false }

// Temporary indicates an expected call of Temporary.
func (mr *MockErrorMockRecorder) Temporary() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Timeout mocks base method.
func (m *MockError) Timeout() bool { _ = "STUB: not implemented"; return false }

// Timeout indicates an expected call of Timeout.
func (mr *MockErrorMockRecorder) Timeout() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockConn is a mock of Conn interface.
type MockConn struct {
	ctrl     *gomock.Controller
	recorder *MockConnMockRecorder
}

// MockConnMockRecorder is the mock recorder for MockConn.
type MockConnMockRecorder struct {
	mock *MockConn
}

// NewMockConn creates a new mock instance.
func NewMockConn(ctrl *gomock.Controller) *MockConn { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConn) EXPECT() *MockConnMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockConn) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockConnMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// LocalAddr mocks base method.
func (m *MockConn) LocalAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// LocalAddr indicates an expected call of LocalAddr.
func (mr *MockConnMockRecorder) LocalAddr() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Read mocks base method.
func (m *MockConn) Read(arg0 []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// Read indicates an expected call of Read.
func (mr *MockConnMockRecorder) Read(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoteAddr mocks base method.
func (m *MockConn) RemoteAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// RemoteAddr indicates an expected call of RemoteAddr.
func (mr *MockConnMockRecorder) RemoteAddr() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SetDeadline mocks base method.
func (m *MockConn) SetDeadline(arg0 time.Time) error { _ = "STUB: not implemented"; return nil }

// SetDeadline indicates an expected call of SetDeadline.
func (mr *MockConnMockRecorder) SetDeadline(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetReadDeadline mocks base method.
func (m *MockConn) SetReadDeadline(arg0 time.Time) error { _ = "STUB: not implemented"; return nil }

// SetReadDeadline indicates an expected call of SetReadDeadline.
func (mr *MockConnMockRecorder) SetReadDeadline(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetWriteDeadline mocks base method.
func (m *MockConn) SetWriteDeadline(arg0 time.Time) error { _ = "STUB: not implemented"; return nil }

// SetWriteDeadline indicates an expected call of SetWriteDeadline.
func (mr *MockConnMockRecorder) SetWriteDeadline(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Write mocks base method.
func (m *MockConn) Write(arg0 []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// Write indicates an expected call of Write.
func (mr *MockConnMockRecorder) Write(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
